<div class="top-content-home">

	<div class="banner-top-home" style="margin:0px">

		<div class="container-fluid">

			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_top')->toHtml();?>

		</div>

	</div>



	<div class="onsale-home">

		<div class="container">

			<?php echo $block->getLayout()->createBlock('Rokanthemes\Onsaleproduct\Block\Onsaleproduct')->setTemplate('Rokanthemes_Onsaleproduct::onsaleproduct.phtml')->toHtml();?> 

		</div>

	</div>

	

	

</div>