<div class="footer-container">
	<div class="footer-static-container">
		<div class="container">
			<?php echo $this->getChildHtml("footer_static2"); ?>
		</div>
	</div>
	<div class="footer-copyright">
		<div class="container">
			<div class="container-inner">
				<div class="row">
					<div class="col-md-6 col-xs-12">
						<?php echo $this->getChildHtml("copyright"); ?>
					</div>
					<div class="col-md-6 col-xs-12">
						<?php echo $this->getChildHtml("footer_payment"); ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>